//user
export const ERROR_CREATE_USER_WITH_SOCIAL = 'ERROR_CREATE_USER_WITH_SOCIAL';
export const LOGIN_SOCIAL_SUCCESSFULLY = 'LOGIN_SOCIAL_SUCCESSFULLY';
export const USER_NOT_ACTIVE = 'USER_NOT_ACTIVE';
export const LOGIN_SOCIAL_FAILED = 'LOGIN_SOCIAL_FAILED';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const ACCOUNT_ALREADY_VERIFIED = 'ACCOUNT_ALREADY_VERIFIED';
export const PHONE_NUMBER_HAS_BEEN_USED = 'PHONE_NUMBER_HAS_BEEN_USED';
export const ACCOUNT_IS_BLOCKED = 'ACCOUNT_IS_BLOCKED';
export const ERROR_UPDATE_USER_OTP_PHONE = 'ERROR_UPDATE_USER_OTP_PHONE';
export const ERROR_SAVE_USER = 'ERROR_SAVE_USER';
export const ERROR_CREATE_USER_WITH_PHONE = 'ERROR_CREATE_USER_WITH_PHONE';
export const LOGIN_PHONE_SUCCESSFULLY = 'LOGIN_PHONE_SUCCESSFULLY';
export const REGISTER_PHONE_SUCCESSFULLY = 'REGISTER_PHONE_SUCCESSFULLY';

//otp
export const SEND_OTP_SUCCESSFULLY = 'SEND_OTP_SUCCESSFULLY';
export const ERROR_SEND_OTP_REGISTER_PHONE = 'ERROR_SEND_OTP_REGISTER_PHONE';
export const ERROR_SEND_OTP = 'ERROR_SEND_OTP';
export const OTP_EXPIRED = 'OTP_EXPIRED';
export const ERROR_VERIFY_OTP = 'ERROR_VERIFY_OTP';
export const OTP_INVALID = 'OTP_INVALID';
